/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 A2009JF1.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function A2009JF1(props) {
  const { nodes, materials } = useGLTF('/public/models/A2009JF1.gltf')
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/public/models/A2009JF1.gltf')
