/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 A20000SG344.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function A20000SG344(props) {
  const { nodes, materials } = useGLTF('/public/models/A20000SG344.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} scale={[0.422, 1, 0.859]} />
    </group>
  )
}

useGLTF.preload('/public/models/A20000SG344.gltf')
