/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 A2018VP1.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function A2018VP1(props) {
  const { nodes, materials } = useGLTF('/public/models/A2018VP1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/public/models/A2018VP1.gltf')
