/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 AATOM.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AATOM(props) {
  const { nodes, materials } = useGLTF('/public/models/AATOM.gltf')
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/public/models/AATOM.gltf')
