/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Asteroide2006QU89.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Asteroide2006QU89(props) {
  const { nodes, materials } = useGLTF('/public/models/Asteroide2006QU89.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} scale={[0.549, 0.754, 0.624]} />
    </group>
  )
}

useGLTF.preload('/public/models/Asteroide2006QU89.gltf')
