/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Asteroide2008JL3.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Asteroide2008JL3(props) {
  const { nodes, materials } = useGLTF('/public/models/Asteroide2008JL3.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/public/models/Asteroide2008JL3.gltf')
